services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      # Use the service name 'db' as the hostname for the database connection
      # Override the .env DATABASE_URL to use the internal docker network hostname 'db'
      - DATABASE_URL=postgresql://pharma_user:${POSTGRES_PASSWORD}@db:5432/pharma_db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    command: sh -c "npx --yes prisma migrate deploy && node server.js"
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - pharma_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=pharma_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=pharma_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharma_network

volumes:
  postgres_data:


networks:
  pharma_network:
